Fix issue - not showing resources tree in modx manager.
This fix for error "TypeError: s[i].search is not a function" in `manager/assets/modext/widgets/core/tree/modx.tree.js` file on line 421 `sr = s[i].search(p);`. This is because first argument of `s` is not string. Better check "if `s[i]` is string or not" fix this issue.
Screenshot from chrome debugger: https://yadi.sk/i/tUA6CT2h3AcoNk